/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'carId' : bigint,
  'name' : string,
  'email' : string,
  'preferredDate' : string,
  'phone' : string,
}
export interface Car {
  'id' : bigint,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'acceleration' : string,
  'category' : Category,
  'price' : bigint,
  'topSpeed' : bigint,
  'horsepower' : bigint,
}
export type Category = { 'suv' : null } |
  { 'sedan' : null } |
  { 'sports' : null } |
  { 'electric' : null };
export interface _SERVICE {
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllCars' : ActorMethod<[], Array<Car>>,
  'getCarById' : ActorMethod<[bigint], Car>,
  'getCarsByCategory' : ActorMethod<[Category], Array<Car>>,
  'getFeaturedCars' : ActorMethod<[], Array<Car>>,
  'submitBooking' : ActorMethod<
    [string, string, string, bigint, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];