/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'carId' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
});
export const Category = IDL.Variant({
  'suv' : IDL.Null,
  'sedan' : IDL.Null,
  'sports' : IDL.Null,
  'electric' : IDL.Null,
});
export const Car = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'acceleration' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
  'topSpeed' : IDL.Nat,
  'horsepower' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getCarById' : IDL.Func([IDL.Nat], [Car], ['query']),
  'getCarsByCategory' : IDL.Func([Category], [IDL.Vec(Car)], ['query']),
  'getFeaturedCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'carId' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Category = IDL.Variant({
    'suv' : IDL.Null,
    'sedan' : IDL.Null,
    'sports' : IDL.Null,
    'electric' : IDL.Null,
  });
  const Car = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'acceleration' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
    'topSpeed' : IDL.Nat,
    'horsepower' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getCarById' : IDL.Func([IDL.Nat], [Car], ['query']),
    'getCarsByCategory' : IDL.Func([Category], [IDL.Vec(Car)], ['query']),
    'getFeaturedCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };